- hosts: local
  become: yes
  tasks:
    # post installation steps found at https://jenkins.io/doc/book/installing/ 
    # always try to use HTTPS.
    # https://jenkins.io/doc/book/installing/ - debian/ubuntu
    - apt_key: url=https://pkg.jenkins.io/debian/jenkins.io.key state=present 
    - apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' state=present filename='jenkins' update_cache='yes'
    - apt: name='jenkins' state='present' update_cache='yes'