---

- name: run the playbook tasks on the localhost
  hosts: local
  become: yes
  tasks:

  - name: print out the hostname of target
    command: hostname
  
  - name: ensure exfat-fuse and exfat-utils are installed
    command: apt-get -y install exfat-fuse exfat-utils
  
  - name: update the apt package index i.e. apt-get update
    apt: update_cache=yes

  # - name: upgrade system packages i.e. apt-get upgrade
  #   apt: upgrade=yes 